# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Maven@3
      inputs:
        mavenPOMFile: 'pom.xml'
        goals: package
        options: clean -DskipTests 
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: buildAndPush
        dockerfile: '$(Build.SourcesDirectory)/src/main/docker/Dockerfile.jvm'
        arguments: -t quarkus/demo-rest-json-jvm
        buildContext: '$(Build.SourcesDirectory)'
        repository: 'quarkus-az-pipeline'
        containerRegistry: 'QuarkusIoRegistry'
        tags: |
          $(tag)
