# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Maven@3
      displayName: Contruccion de artefacto con Maven
      inputs:
        mavenPOMFile: 'pom.xml'
        goals: package
        options: clean -DskipTests 
    - task: Docker@2
      displayName: Construir imagen con Red Hat Universal Base Image (UBI)
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/src/main/docker/Dockerfile.jvm'
        containerRegistry: $(serviceConnection)
        buildContext: '$(Build.SourcesDirectory)'
        repository: $(imageName)
        tags: |
          $(tag)
          latest
    - task: Docker@2
      displayName: Publicar imagen en Quay.io
      inputs:
        command: push
        repository: $(imageName)
        containerRegistry: $(serviceConnection)
        tags: |
          $(tag)
          latest
